/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
  _key: string;
} | {
  language?: "typescript" | "javascript" | "tsx" | "html" | "css" | "json" | "bash" | "groq";
  filename?: string;
  code: string;
  _type: "codeSnippet";
  _key: string;
} | {
  tone?: "tip" | "info" | "warning";
  text: string;
  _type: "callout";
  _key: string;
}>;

export type Resource = {
  _type: "resource";
  title: string;
  description?: string;
  type: "PDF" | "Code" | "Guide" | "Link" | "Video";
  url: string;
  fileSize?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  title: string;
  description?: string;
  icon?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<{
    _key: string;
  } & LessonReference>;
};

export type ProgressRecord = {
  _id: string;
  _type: "progressRecord";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId: string;
  completedLessons?: Array<{
    _key: string;
  } & LessonReference>;
  lastLesson?: LessonReference;
  lastPositionSeconds?: number;
  updatedAt?: string;
};

export type AgentContext = {
  _id: string;
  _type: "agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  scopeFilter?: string;
  instructions?: string;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  videoId: string;
  url: string;
  provider?: "youtube" | "vimeo" | "bunny";
  chapters?: Array<{
    startSeconds: number;
    label: string;
    _type: "chapter";
    _key: string;
  }>;
  chunks?: Array<{
    startSeconds: number;
    text: string;
    _type: "transcriptChunk";
    _key: string;
  }>;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  duration: string;
  durationSeconds?: number;
  freePreview?: boolean;
  studentCount?: number;
  keyPoints?: Array<string>;
  proTip?: string;
  notes?: BlockContent;
  resources?: Array<{
    _key: string;
  } & Resource>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  badgeIcon?: "nextjs" | "typescript" | "docker" | "react" | "python" | "database";
  level: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
  duration?: string;
  price?: number;
  popular?: boolean;
  studentCount?: number;
  instructor: InstructorReference;
  category: CategoryReference;
  learningOutcomes?: Array<{
    _key: string;
  } & LearningOutcome>;
  modules?: Array<{
    _key: string;
  } & Module>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | BlockContent | Resource | LearningOutcome | LessonReference | Module | ProgressRecord | AgentContext | Video | Lesson | SanityImageCrop | SanityImageHotspot | Slug | InstructorReference | CategoryReference | Course | Category | Instructor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: allCoursesQuery
// Query: *[_type == "course"] | order(_createdAt desc) {    _id,    title,    slug,    summary,    coverImage,    badgeIcon,    level,    duration,    price,    popular,    studentCount,    "instructor": instructor->{      _id,      name,      expertise,      photo    },    "category": category->{      _id,      title,      slug    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[])  }
export type AllCoursesQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  badgeIcon: "database" | "docker" | "nextjs" | "python" | "react" | "typescript" | null;
  level: "Advanced" | "All Levels" | "Beginner" | "Intermediate";
  duration: string | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  instructor: {
    _id: string;
    name: string;
    expertise: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  category: {
    _id: string;
    title: string;
    slug: Slug;
  };
  moduleCount: number | null;
  lessonCount: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: featuredCoursesQuery
// Query: *[_type == "course"] | order(popular desc, _createdAt desc)[0...6] {    _id,    title,    slug,    summary,    coverImage,    badgeIcon,    level,    duration,    price,    popular,    studentCount,    "instructor": instructor->{      _id,      name,      expertise,      photo    },    "category": category->{      _id,      title,      slug    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[])  }
export type FeaturedCoursesQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  badgeIcon: "database" | "docker" | "nextjs" | "python" | "react" | "typescript" | null;
  level: "Advanced" | "All Levels" | "Beginner" | "Intermediate";
  duration: string | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  instructor: {
    _id: string;
    name: string;
    expertise: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  category: {
    _id: string;
    title: string;
    slug: Slug;
  };
  moduleCount: number | null;
  lessonCount: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: courseBySlugQuery
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    _type,    title,    slug,    summary,    coverImage,    badgeIcon,    level,    duration,    price,    popular,    studentCount,    "instructor": instructor->{      _id,      _type,      name,      slug,      photo,      expertise,      bio    },    "category": category->{      _id,      _type,      title,      slug,      description    },    learningOutcomes[]{      _key,      title,      description,      icon    },    modules[]{      _key,      _type,      title,      summary,      lessons[]->{        _id,        title,        slug,        duration,        durationSeconds,        freePreview,        studentCount,        videoUrl      }    },    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[])  }
export type CourseBySlugQueryResult = {
  _id: string;
  _type: "course";
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  badgeIcon: "database" | "docker" | "nextjs" | "python" | "react" | "typescript" | null;
  level: "Advanced" | "All Levels" | "Beginner" | "Intermediate";
  duration: string | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  instructor: {
    _id: string;
    _type: "instructor";
    name: string;
    slug: Slug;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    expertise: string;
    bio: string | null;
  };
  category: {
    _id: string;
    _type: "category";
    title: string;
    slug: Slug;
    description: string | null;
  };
  learningOutcomes: Array<{
    _key: string;
    title: string;
    description: string | null;
    icon: string | null;
  }> | null;
  modules: Array<{
    _key: string;
    _type: "module";
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: Slug;
      duration: string;
      durationSeconds: number | null;
      freePreview: boolean | null;
      studentCount: number | null;
      videoUrl: string;
    }> | null;
  }> | null;
  moduleCount: number | null;
  lessonCount: number | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: lessonBySlugQuery
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    _type,    title,    slug,    videoUrl,    thumbnail,    duration,    durationSeconds,    freePreview,    studentCount,    keyPoints,    proTip,    notes,    resources[]{      _key,      title,      description,      type,      url,      fileSize    },    "course": *[_type == "course" && references(^._id)][0] {      _id,      title,      slug,      "instructor": instructor->{        name,        expertise,        photo      },      modules[]{        _key,        title,        summary,        lessons[]->{          _id,          title,          slug,          duration,          freePreview        }      }    }  }
export type LessonBySlugQueryResult = {
  _id: string;
  _type: "lesson";
  title: string;
  slug: Slug;
  videoUrl: string;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  duration: string;
  durationSeconds: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  notes: BlockContent | null;
  resources: Array<{
    _key: string;
    title: string;
    description: string | null;
    type: "Code" | "Guide" | "Link" | "PDF" | "Video";
    url: string;
    fileSize: string | null;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: Slug;
    instructor: {
      name: string;
      expertise: string;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
    };
    modules: Array<{
      _key: string;
      title: string;
      summary: string | null;
      lessons: Array<{
        _id: string;
        title: string;
        slug: Slug;
        duration: string;
        freePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: allInstructorsQuery
// Query: *[_type == "instructor"] | order(name asc) {    _id,    _type,    name,    slug,    photo,    expertise,    bio  }
export type AllInstructorsQueryResult = Array<{
  _id: string;
  _type: "instructor";
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise: string;
  bio: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: instructorBySlugQuery
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    _type,    name,    slug,    photo,    expertise,    bio,    "courses": *[_type == "course" && references(^._id)] | order(_createdAt desc) {      _id,      title,      slug,      summary,      coverImage,      badgeIcon,      level,      duration,      price,      popular,      studentCount,      "category": category->{        title,        slug      },      "moduleCount": count(modules),      "lessonCount": count(modules[].lessons[])    }  }
export type InstructorBySlugQueryResult = {
  _id: string;
  _type: "instructor";
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise: string;
  bio: string | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: Slug;
    summary: string;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    badgeIcon: "database" | "docker" | "nextjs" | "python" | "react" | "typescript" | null;
    level: "Advanced" | "All Levels" | "Beginner" | "Intermediate";
    duration: string | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    category: {
      title: string;
      slug: Slug;
    };
    moduleCount: number | null;
    lessonCount: number | null;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: allCategoriesQuery
// Query: *[_type == "category"] | order(title asc) {    _id,    _type,    title,    slug,    description,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type AllCategoriesQueryResult = Array<{
  _id: string;
  _type: "category";
  title: string;
  slug: Slug;
  description: string | null;
  courseCount: number;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: homepageCoursesQuery
// Query: *[_type == "course" && slug.current in [    "nextjs-app-router-in-depth",    "nextjs-for-production",    "devops-with-docker-and-kubernetes",    "typescript-for-application-developers"  ]] {    _id,    title,    slug,    summary,    coverImage,    badgeIcon,    level,    duration,    price,    popular,    studentCount,    "moduleCount": count(modules),    "lessonCount": count(modules[].lessons[])  }
export type HomepageCoursesQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  badgeIcon: "database" | "docker" | "nextjs" | "python" | "react" | "typescript" | null;
  level: "Advanced" | "All Levels" | "Beginner" | "Intermediate";
  duration: string | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  moduleCount: number | null;
  lessonCount: number | null;
}>;

